# -*- coding: utf-8 -*-
"""Armstrong number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s78roMaHaZ8ptBxsZF0Brdn5WC-JOnF1
"""

num=int(input("enter a number"))
n=num
sum=0
while n>0:
  dig=n%10
  sum+=dig**3
  n//=10
if num == sum:
   print(num,"is an Armstrong number")
else:
   print(num,"is not an Armstrong number")