# -*- coding: utf-8 -*-
"""practical 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18P-XQbU-zmkAHeDvzCGF_ePc946FeYYB
"""

"""Exp. 4:-Write a python program that accepts a string from user and perform following string operations-
1. Calculate length of string
2. String reversal
3. Equality check of two strings
4. Check palindrome
NAME-RUTUJA NAIK
ROLL NO-70
SECTION -C"""
print("1. Calculate length of string")
print("2. String reversal")
print("3. Equality check of two strings")
print("4. Check palindrome")
c=int(input("enter your choice(1,2,3,4):"))
def length(s):
  l=len(s)
  print("The length of string is",l)
def reverse(s):
  r=s[::-1]
  print("The reversed string is",r)
def equal(s):
  s1=str(input("enter another string:"))
  if s==s1:
    print("The two strings are equal.")
  else:
    print("The two strings are not equal.")
def palindrome(s):
  r=s[::-1]
  s.upper()
  r.upper()
  if s==r:
    print(s,"is a palindrome.")
  else:
    print(s,"is a not palindrome.")
if c==1:
  s=str(input("enter a string:"))
  length(s)
elif c==2:
  s=str(input("enter a string:"))
  reverse(s)
elif c==3:
  s=str(input("enter a string:"))
  equal(s)
elif c==4:
  s=str(input("enter a string:"))
  palindrome(s)
else:
  print("Invalid Choice")
print("RUTUJA NAIK")
print("C-70")