# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1saVmuZMiSJhnvot2MxNYFeSHF2G9Stni
"""

import pandas as pd
import matplotlib.pyplot as plt
exam={"name":["arya","bhavya","charvi","daksh","ekta","faiz","ganesh","harsh","isha","jonita"],
     "roll_no":[1,2,3,4,5,6,7,8,9,10],
     "marks":[10,20,30,40,50,60,70,80,90,100]}
df=pd.DataFrame(exam)
df