# -*- coding: utf-8 -*-
"""python -if -else statements

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13D8RqJm-7es82DB0g3w-9K5x6McrZeuV
"""

#Write a Python program to check if a number is  between 1 to 9
n=int(input("enter a number:"))
if n in range(1,10):
  print("the number is  between 1 to 9")
else:
  print("the number is not between 1 to 9")