# -*- coding: utf-8 -*-
"""python code

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13D8RqJm-7es82DB0g3w-9K5x6McrZeuV
"""

i=int(input())
d=float(input())
s=str(input())
i1=int(input())
d1=float(input())
s1=str(input())
# Print the sum of both integer variables on a new line.
print(i+i1)
# Print the sum of the double variables on a new line.
print(d+d1)
# Concatenate and print the String variables on a new line
print(s+s1)