# -*- coding: utf-8 -*-
"""python -if -else statements

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13D8RqJm-7es82DB0g3w-9K5x6McrZeuV
"""

#Write a Python program to find those numbers which are divisible by 7 and multiple of 5, between 1500 and 2700 (both included).
print("numbers which are divisible by 7 and multiple of 5 are:")    
for i in range(1500,2701):
  if i%7==0 and i%5==0:
    print (i)